---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes
  run_once: true

- name: Install common packages
  apt:
    name:
      - curl
      - git
      - vim
    state: present
  become: yes